version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas : 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role != manager
    volumes:
      - redis_data:/data

  flask-app:
    image: "radunichita/ssi-project:latest"
    ports:
      - "5000:5000"
    depends_on:
      - redis
    deploy:
      replicas : 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role != manager
  
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: -H unix:///var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - flask-app
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: webscrapper-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
    env_file:
      - ./env/config.monitoring
    depends_on:
      - prometheus
    deploy:
      placement:
        constraints:
          - node.role == manager


volumes:
  redis_data:
  portainer_data: