name: Python Lint

on:
  pull_request:
  push:
    branches:
      - main  # change this to your main branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # change this to your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint Python code
      run: flake8 --ignore=E501,E711,W293,F403,F405 main.py